-- Create Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  image_url TEXT,
  category TEXT,
  sizes TEXT[] DEFAULT '{}',
  is_new BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert Velora Products
INSERT INTO products (name, description, price, image_url, category, sizes, is_new)
VALUES 
('AeroFit Performance Tee', 'Lightweight, breathable tee designed for everyday movement and all-day comfort.', 49.00, '/aerofit-performance-tee.png', 'Tops', ARRAY['S', 'M', 'L', 'XL'], true),
('Flux Oversized Hoodie', 'Relaxed-fit hoodie with soft fleece lining, built for comfort and a modern silhouette.', 89.00, '/flux-oversized-hoodie.png', 'Hoodies', ARRAY['S', 'M', 'L', 'XL'], true),
('CoreFlex Slim Joggers', 'Tapered joggers with stretch fabric for a clean look and unrestricted movement.', 79.00, '/coreflex-joggers.png', 'Bottoms', ARRAY['S', 'M', 'L', 'XL'], false),
('Nova Utility Jacket', 'Structured lightweight jacket with functional pockets and a sharp urban finish.', 129.00, '/nova-utility-jacket.png', 'Outerwear', ARRAY['M', 'L', 'XL'], true),
('Drift Relaxed Shirt', 'Casual button-up shirt with a relaxed fit, perfect for layering or standalone wear.', 69.00, '/drift-relaxed-shirt.png', 'Outwear', ARRAY['S', 'M', 'L', 'XL'], false);

-- Create Cart Table (fresh install)
CREATE TABLE cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER DEFAULT 1,
  size TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart ENABLE ROW LEVEL SECURITY;

-- Products: anyone can view
CREATE POLICY "Allow public select on products" ON products FOR SELECT USING (true);

-- Cart: users can only access their own rows
CREATE POLICY "Users can view own cart"   ON cart FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own cart" ON cart FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own cart" ON cart FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own cart" ON cart FOR DELETE USING (auth.uid() = user_id);

-- ============================================================
-- MIGRATION (run this if cart table already exists)
-- ============================================================
-- ALTER TABLE cart ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
-- ALTER TABLE cart DROP COLUMN IF EXISTS session_id;
-- DROP POLICY IF EXISTS "Allow public access on cart" ON cart;
-- CREATE POLICY "Users can view own cart"   ON cart FOR SELECT USING (auth.uid() = user_id);
-- CREATE POLICY "Users can insert own cart" ON cart FOR INSERT WITH CHECK (auth.uid() = user_id);
-- CREATE POLICY "Users can update own cart" ON cart FOR UPDATE USING (auth.uid() = user_id);
-- CREATE POLICY "Users can delete own cart" ON cart FOR DELETE USING (auth.uid() = user_id);

-- ============================================================
-- ADMIN PANEL SETUP (run once in Supabase SQL Editor)
-- ============================================================

-- 1. Profiles table (mirrors auth.users, adds is_admin flag)
CREATE TABLE IF NOT EXISTS profiles (
  id         UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email      TEXT,
  is_admin   BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Users can read their own profile
CREATE POLICY "Users can view own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

-- Admins can view ALL profiles
CREATE POLICY "Admins can view all profiles" ON profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.is_admin = true
    )
  );

-- 2. Trigger: auto-create profile row when a new user signs up
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- 3. Allow admins to view ALL cart rows (in addition to own-cart policies)
CREATE POLICY "Admins can view all carts" ON cart
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.is_admin = true
    )
  );

4. Grant yourself admin access (replace with your email)
UPDATE profiles SET is_admin = true WHERE email = 'pandapratyush005@gmail.com';

